name: assignment-test

on: 
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install CMake and Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ruby
      - name: Make unit test script executable
        run: chmod +777 ./unit-test.sh
      - name: Hasan add
        run: chmod +777 ./build/assignment-autotest/assignment-autotest
      - name: Run unit test
        run: ./unit-test.sh

